/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Signup;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.JFrame;


import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;

/**
 *
 * @author ADARSH
 */
public class Dashboard extends javax.swing.JFrame {

    public int choose;
    

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        
         String s1 = null;
            try
            {
                String str="SELECT * FROM AMOUNT";  
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                java.sql.PreparedStatement pstmt= conn.prepareStatement(str);
                ResultSet rs= pstmt.executeQuery(str);
            if(rs.next())
            {
                s1=rs.getString("AMOUNT");
                //left_amnt.setText(s1);
 
            }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            
            }
            left_amnt.setText(s1);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        Background = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_dash = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_exit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        left_amnt = new java.awt.TextField();
        TopPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        kGradientPanel1.setForeground(new java.awt.Color(204, 102, 255));
        kGradientPanel1.setkEndColor(new java.awt.Color(153, 0, 255));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 102, 255));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(54, 39, 89));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(85, 65, 118));

        btn_dash.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_dash.setForeground(new java.awt.Color(255, 255, 255));
        btn_dash.setText("DASHBOARD");
        btn_dash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_dashMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btn_dash)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_dash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        SidePanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 40));

        jPanel3.setBackground(new java.awt.Color(54, 39, 89));

        btn_exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setText("EXIT");
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btn_exit)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        SidePanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("WELCOME!");
        jLabel5.setToolTipText("");
        SidePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("WALLET AMOUNT: -");
        SidePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 120, 20));

        left_amnt.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        left_amnt.setEditable(false);
        left_amnt.setEnabled(false);
        left_amnt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        left_amnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                left_amntMouseClicked(evt);
            }
        });
        left_amnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                left_amntActionPerformed(evt);
            }
        });
        left_amnt.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                left_amntTextValueChanged(evt);
            }
        });
        SidePanel.add(left_amnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 70, -1));

        Background.add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 468));

        TopPanel.setBackground(new java.awt.Color(112, 79, 221));
        TopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MOVIES SCREENING");
        TopPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 350, 40));

        Background.add(TopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 700, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Signup/ar_130x150.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 130, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Signup/ts4_130x150.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Signup/chic.jpg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        Background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, -1, -1));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashMousePressed
        // TODO add your handling code here:
        //jPanel1.setBackground(new Color(85,65,118));
        //jPanel2.setBackground(new Color(54,39,89));
        //jPanel3.setBackground(new Color(54,39,89));
    }//GEN-LAST:event_btn_dashMousePressed

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
        // TODO add your handling code here:
        //jPanel3.setBackground(new Color(85,65,118));
       //jPanel2.setBackground(new Color(54,39,89));
        //jPanel1.setBackground(new Color(54,39,89));
        
    }//GEN-LAST:event_btn_exitMouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        choose=1;
        setVisible(false);
        new Theater_Booking(choose).setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        choose=2;
        setVisible(false);
        new Theater_Booking(choose).setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        choose=3;
        setVisible(false);
        new Theater_Booking(choose).setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void left_amntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_left_amntActionPerformed
           
    }//GEN-LAST:event_left_amntActionPerformed

    private void left_amntTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_left_amntTextValueChanged
        
    }//GEN-LAST:event_left_amntTextValueChanged

    private void left_amntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_left_amntMouseClicked
        
            String s1 = null;
            try
            {
                String str="SELECT * FROM AMOUNT";  
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                java.sql.PreparedStatement pstmt= conn.prepareStatement(str);
                ResultSet rs= pstmt.executeQuery(str);
            if(rs.next())
            {
                s1=rs.getString("AMOUNT");
                //left_amnt.setText(s1);
 
            }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            
            }
            left_amnt.setText(s1);
    
    }//GEN-LAST:event_left_amntMouseClicked

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JLabel btn_dash;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private java.awt.TextField left_amnt;
    // End of variables declaration//GEN-END:variables
}
