package Signup;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @Sushma
 */

public class Theater_Booking extends javax.swing.JFrame{
    int m;
    private Border XPEmptyBorder;
    /**
     * Creates new form Theater_Booking
     */
    public Theater_Booking(){
       // getContentPane().setBackground(Color.orange);
        initComponents();
    }
    public Theater_Booking(int num)
    {
        m=num;
        initComponents();
        if(num==1)
        {
            jTextField3.setText("ARJUN REDDY");
            try
            {
                String str="SELECT * FROM ARJUN_REDDY";  
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                java.sql.PreparedStatement pstmt= conn.prepareStatement(str);
                ResultSet rs= pstmt.executeQuery(str);
            if(rs.next())
            {
                String s1,s2,s3,s4;
                s1 = rs.getString("STALL");
                stall.setText(s1);
                s2 = rs.getString("CIRCLE");
                circle.setText(s2);
                s3 = rs.getString("BOX");
                box1.setText(s3);
                s4 = rs.getString("UPPER");
                upper.setText(s4);
 
            }
            }
            catch(ClassNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
        }
            
        if(num==2)
        {
            jTextField3.setText("TOY STORY 4");
            try
            {
                String str="SELECT * FROM TOY_STORY";          
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                java.sql.PreparedStatement pstmt= conn.prepareStatement(str);
                ResultSet rs= pstmt.executeQuery(str);
            if(rs.next())
            {
                String s1,s2,s3,s4;
                s1 = rs.getString("STALL");
                stall.setText(s1);
                s2 = rs.getString("CIRCLE");
                circle.setText(s2);
                s3 = rs.getString("BOX");
                box1.setText(s3);
                s4 = rs.getString("UPPER");
                upper.setText(s4);
            }
            }
            catch(ClassNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
        }
            
        if(num==3)
        {
            jTextField3.setText("CHHICHHORE");
            try
            {
                String str="SELECT * FROM CHHICHHORE";          
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                java.sql.PreparedStatement pstmt= conn.prepareStatement(str);
                ResultSet rs= pstmt.executeQuery(str);
            if(rs.next())
            {
                String s1,s2,s3,s4;
                s1 = rs.getString("STALL");
                stall.setText(s1);
                s2 = rs.getString("CIRCLE");
                circle.setText(s2);
                s3 = rs.getString("BOX");
                box1.setText(s3);
                s4 = rs.getString("UPPER");
                upper.setText(s4);
            }
            }
            catch(ClassNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
        }
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSpinner1 = new javax.swing.JSpinner();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        Seat_type = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        seats = new java.awt.TextField();
        stall = new java.awt.TextField();
        circle = new java.awt.TextField();
        upper = new java.awt.TextField();
        kButton2 = new keeptoo.KButton();
        box1 = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 102, 0));
        setMinimumSize(new java.awt.Dimension(420, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setBorder(XPEmptyBorder);
        kGradientPanel1.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel1.setkGradientFocus(150);
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 0, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Seat_type.setBackground(new java.awt.Color(216, 191, 216));
        Seat_type.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select seat type: -");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Stall");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Circle");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Upper");
        jRadioButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton3.setOpaque(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Box");
        jRadioButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton4.setOpaque(false);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Seat_typeLayout = new javax.swing.GroupLayout(Seat_type);
        Seat_type.setLayout(Seat_typeLayout);
        Seat_typeLayout.setHorizontalGroup(
            Seat_typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Seat_typeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Seat_typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Seat_typeLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(Seat_typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Seat_typeLayout.setVerticalGroup(
            Seat_typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Seat_typeLayout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4))
        );

        kGradientPanel1.add(Seat_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 259, 130, 130));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Movie name: -");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0,0,0,0));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("ARJUN REDDY");
        jTextField3.setBorder(null);
        jTextField3.setOpaque(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 140, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter no. of seats: -");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 150, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Price/Ticket");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, 20));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0,0,0,0));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField2.setOpaque(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 30, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Exit\n");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Back");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 255));
        jLabel1.setText("DETAILS");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 150, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Seats available: -");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 150, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Stall: - ");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 50, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Upper: -");
        kGradientPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 56, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Circle: -");
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 52, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Box: -");
        kGradientPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));
        kGradientPanel1.add(seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 60, -1));

        stall.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        stall.setEditable(false);
        stall.setEnabled(false);
        stall.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stallActionPerformed(evt);
            }
        });
        kGradientPanel1.add(stall, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 60, -1));

        circle.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        circle.setEditable(false);
        circle.setEnabled(false);
        circle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        circle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleActionPerformed(evt);
            }
        });
        kGradientPanel1.add(circle, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 60, -1));

        upper.setEditable(false);
        upper.setEnabled(false);
        upper.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kGradientPanel1.add(upper, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 60, -1));

        kButton2.setText("Book tickets");
        kButton2.setkEndColor(new java.awt.Color(0, 255, 153));
        kButton2.setkHoverColor(new java.awt.Color(0, 153, 153));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkStartColor(new java.awt.Color(153, 153, 255));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 90, 30));

        box1.setEditable(false);
        box1.setEnabled(false);
        box1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kGradientPanel1.add(box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 60, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
if(jRadioButton3.isSelected())
    jTextField2.setText(""+300);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        int Seat=Integer.parseInt(seats.getText());
        int Price=Integer.parseInt(jTextField2.getText());
        int totalamt=Seat*Price;
        jTextField2.setText(Integer.toString(totalamt));
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
if(jRadioButton1.isSelected())
    jTextField2.setText(""+50);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
if(jRadioButton2.isSelected())
    jTextField2.setText(""+150);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
if(jRadioButton4.isSelected())
    jTextField2.setText(""+500);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
        int Seat=Integer.parseInt(seats.getText());
        int Price=Integer.parseInt(jTextField2.getText());
        int totalamt=Seat*Price;
        int cash = 0;
        int remaining;
        //jTextField2.setText(Integer.toString(totalamt));
        try
        {
            String amount="SELECT * FROM AMOUNT";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
            java.sql.PreparedStatement pstmt= conn.prepareStatement(amount);
            ResultSet rs= pstmt.executeQuery(amount);
            if(rs.next())
            {
                String amt = rs.getString("AMOUNT");
                cash=Integer.parseInt(amt);
            }
            
        }
        catch(ClassNotFoundException | NumberFormatException | SQLException e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
        remaining=cash-totalamt;
        try
        {
            String amount;
            amount = "UPDATE AMOUNT SET AMOUNT=?";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
            java.sql.PreparedStatement pstmt= conn.prepareStatement(amount);
            pstmt.setInt(1,remaining);
            System.out.println(pstmt);
            pstmt.executeUpdate();
            
        }
        catch(ClassNotFoundException | NumberFormatException | SQLException e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
                        
        if(jRadioButton1.isSelected() && m==1)
        {
            int a1,a2,a3;
            a1=Integer.parseInt(seats.getText());
            //jLabel5.setText(Integer.toString(a1));
            a2=Integer.parseInt(stall.getText());
            //jLabel9.setText(Integer.toString(a2));
            a3=a2-a1;
                
            try
            {
                String str1="UPDATE ARJUN_REDDY SET STALL=? WHERE ID=?;";          
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                PreparedStatement pstmt= conn.prepareStatement(str1);
                pstmt.setInt(1,a3);
                pstmt.setInt(2,1);
                System.out.println(pstmt);
                pstmt.executeUpdate();
                //conn.close();
            }
            catch(ClassNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
                //}
        }
        else if(jRadioButton2.isSelected() && m==1)
        {
                
            int a1,a2,a3;
            a1=Integer.parseInt(seats.getText());
            //jLabel5.setText(Integer.toString(a1));
            a2=Integer.parseInt(circle.getText());
            //jLabel9.setText(Integer.toString(a2));
            a3=a2-a1;
                
            try
            {
                String str1="UPDATE ARJUN_REDDY SET CIRCLE=? WHERE ID=?;";          
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                PreparedStatement pstmt= conn.prepareStatement(str1);
                pstmt.setInt(1,a3);
                pstmt.setInt(2,1);
                System.out.println(pstmt);
                pstmt.executeUpdate();
                //conn.close();
            }
            catch(ClassNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
                //}
        }
        else if(jRadioButton3.isSelected() && m==1)
        {
                
            int a1,a2,a3;
            a1=Integer.parseInt(seats.getText());
            //jLabel5.setText(Integer.toString(a1));
            a2=Integer.parseInt(upper.getText());
            //jLabel9.setText(Integer.toString(a2));
            a3=a2-a1;
                
            try
            {
                String str1="UPDATE ARJUN_REDDY SET UPPER=? WHERE ID=?;";          
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                PreparedStatement pstmt= conn.prepareStatement(str1);
                pstmt.setInt(1,a3);
                pstmt.setInt(2,1);
                System.out.println(pstmt);
                pstmt.executeUpdate();
                //conn.close();
            }
            catch(ClassNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
                //}
        }
        else if(jRadioButton4.isSelected() && m==1)
        {
                
            int a1,a2,a3;
            a1=Integer.parseInt(seats.getText());
            //jLabel5.setText(Integer.toString(a1));
            a2=Integer.parseInt(box1.getText());
            //jLabel9.setText(Integer.toString(a2));
            a3=a2-a1;
                
            try
            {
                String str1="UPDATE ARJUN_REDDY SET BOX=? WHERE ID=?;";          
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                PreparedStatement pstmt= conn.prepareStatement(str1);
                pstmt.setInt(1,a3);
                pstmt.setInt(2,1);
                System.out.println(pstmt);
                pstmt.executeUpdate();
                //conn.close();
            }
            catch(ClassNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
                //}
        }
        else if(jRadioButton1.isSelected() && m==2)
        {
                
            int a1,a2,a3;
            a1=Integer.parseInt(seats.getText());
            //jLabel5.setText(Integer.toString(a1));
            a2=Integer.parseInt(stall.getText());
            //jLabel9.setText(Integer.toString(a2));
            a3=a2-a1;
                
            try
            {
                String str1="UPDATE TOY_STORY SET STALL=? WHERE ID=?;";          
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                PreparedStatement pstmt= conn.prepareStatement(str1);
                pstmt.setInt(1,a3);
                pstmt.setInt(2,1);
                System.out.println(pstmt);
                pstmt.executeUpdate();
                //conn.close();
            }
            catch(ClassNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
                //}
        }
        else if(jRadioButton2.isSelected() && m==2)
        {
                
            int a1,a2,a3;
            a1=Integer.parseInt(seats.getText());
            //jLabel5.setText(Integer.toString(a1));
            a2=Integer.parseInt(circle.getText());
            //jLabel9.setText(Integer.toString(a2));
            a3=a2-a1;
                
            try
            {
                String str1="UPDATE TOY_STORY SET CIRCLE=? WHERE ID=?;";          
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                PreparedStatement pstmt= conn.prepareStatement(str1);
                pstmt.setInt(1,a3);
                pstmt.setInt(2,1);
                System.out.println(pstmt);
                pstmt.executeUpdate();
                //conn.close();
            }
            catch(ClassNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
                //}
        }
        else if(jRadioButton3.isSelected() && m==2)
        {
                
            int a1,a2,a3;
            a1=Integer.parseInt(seats.getText());
            //jLabel5.setText(Integer.toString(a1));
            a2=Integer.parseInt(upper.getText());
            //jLabel9.setText(Integer.toString(a2));
            a3=a2-a1;
                
            try
            {
                String str1="UPDATE TOY_STORY SET UPPER=? WHERE ID=?;";          
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                PreparedStatement pstmt= conn.prepareStatement(str1);
                pstmt.setInt(1,a3);
                pstmt.setInt(2,1);
                System.out.println(pstmt);
                pstmt.executeUpdate();
                //conn.close();
            }
            catch(ClassNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
                //}
        }
        else if(jRadioButton4.isSelected() && m==2)
        {
                
            int a1,a2,a3;
            a1=Integer.parseInt(seats.getText());
            //jLabel5.setText(Integer.toString(a1));
            a2=Integer.parseInt(box1.getText());
            //jLabel9.setText(Integer.toString(a2));
            a3=a2-a1;
                
            try
            {
                String str1="UPDATE TOY_STORY SET BOX=? WHERE ID=?;";          
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                PreparedStatement pstmt= conn.prepareStatement(str1);
                pstmt.setInt(1,a3);
                pstmt.setInt(2,1);
                System.out.println(pstmt);
                pstmt.executeUpdate();
                //conn.close();
            }
            catch(ClassNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
                //}
        }
       else if(jRadioButton1.isSelected() && m==3)
        {
                
            int a1,a2,a3;
            a1=Integer.parseInt(seats.getText());
            //jLabel5.setText(Integer.toString(a1));
            a2=Integer.parseInt(stall.getText());
            //jLabel9.setText(Integer.toString(a2));
            a3=a2-a1;
                
            try
            {
                String str1="UPDATE CHHICHHORE SET STALL=? WHERE ID=?;";          
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                PreparedStatement pstmt= conn.prepareStatement(str1);
                pstmt.setInt(1,a3);
                pstmt.setInt(2,1);
                System.out.println(pstmt);
                pstmt.executeUpdate();
                //conn.close();
            }
            catch(ClassNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
                //}
        }
       else if(jRadioButton2.isSelected() && m==3)
        {
                
           int a1,a2,a3;
            a1=Integer.parseInt(seats.getText());
            //jLabel5.setText(Integer.toString(a1));
            a2=Integer.parseInt(circle.getText());
            //jLabel9.setText(Integer.toString(a2));
            a3=a2-a1;
                
            try
            {
                String str1="UPDATE CHHICHHORE SET CIRCLE=? WHERE ID=?;";          
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                PreparedStatement pstmt= conn.prepareStatement(str1);
                pstmt.setInt(1,a3);
                pstmt.setInt(2,1);
                System.out.println(pstmt);
                pstmt.executeUpdate();
                //conn.close();
            }
            catch(ClassNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
                //}
        }
       else if(jRadioButton3.isSelected() && m==3)
        {
                
            int a1,a2,a3;
            a1=Integer.parseInt(seats.getText());
            //jLabel5.setText(Integer.toString(a1));
            a2=Integer.parseInt(upper.getText());
            //jLabel9.setText(Integer.toString(a2));
            a3=a2-a1;
                
            try
            {
                String str1="UPDATE CHHICHHORE SET UPPER=? WHERE ID=?;";          
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                PreparedStatement pstmt= conn.prepareStatement(str1);
                pstmt.setInt(1,a3);
                pstmt.setInt(2,1);
                System.out.println(pstmt);
                pstmt.executeUpdate();
                //conn.close();
            }
            catch(ClassNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
                //}
        }
       else if(jRadioButton4.isSelected() && m==3)
        {
                
            int a1,a2,a3;
            a1=Integer.parseInt(seats.getText());
            //jLabel5.setText(Integer.toString(a1));
            a2=Integer.parseInt(box1.getText());
            //jLabel9.setText(Integer.toString(a2));
            a3=a2-a1;
                
            try
            {
                String str1="UPDATE CHHICHHORE SET BOX=? WHERE ID=?;";          
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project","root","Mysql046");
                PreparedStatement pstmt= conn.prepareStatement(str1);
                pstmt.setInt(1,a3);
                pstmt.setInt(2,1);
                System.out.println(pstmt);
                pstmt.executeUpdate();
                //conn.close();
            }
            catch(ClassNotFoundException | SQLException e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
                //}
        }
        
       JOptionPane.showMessageDialog(this,"Success! You have booked your ticket\n Total amount is "+totalamt);
    }//GEN-LAST:event_kButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0); 
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        Dashboard opt= new Dashboard();
        opt.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void stallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stallActionPerformed

    private void circleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_circleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Theater_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Theater_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Theater_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Theater_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Theater_Booking().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Seat_type;
    private java.awt.TextField box1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private java.awt.TextField circle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private keeptoo.KButton kButton2;
    public keeptoo.KGradientPanel kGradientPanel1;
    private java.awt.TextField seats;
    private java.awt.TextField stall;
    private java.awt.TextField upper;
    // End of variables declaration//GEN-END:variables
}